### ISSUE TITLE
New customer creates a new state and country in Database

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/CCIA#32]
Run this before and after you add a new customer
SELECT * FROM countries
SELECT * FROM my_customers
--DELETE from countries WHERE country_id > 60
--DELETE from state_province WHERE StateProvinceID > 165
--DELETE FROM county WHERE county_id > 9181
select * from state_province

Only the my_customers count should change.

**Comment by jcubbage** [comment]
Google ViewModel MVC. We have examples in the models folder (e.g. https://github.com/ucdavis/CCIA/blob/master/CCIA/Models/BulkSalesCertificateViewModels/BulkSalesCreateViewModel.cs )

You should create a MyCustomerCreateViewModel, with a MyCustomer and List<StateProvince>, <Countries>, <County>. Those should not be in the regular model, even when marked NotMapped.

The way it's done now, those lists are coming back with incorrect  countries, counties, and states, and the selected row is getting added to the country, county, and state table.

**Comment by jcubbage** [comment]
This is why you needed these lines:
 myCustomer.Country.Code = "";
            myCustomer.County.DateModified = DateTime.Now;
            myCustomer.State.DateModified = DateTime.Now;

Those are required fields on Country (in the database, not model), and the way it's written, a new country, county, and state are being created. If the model where correctly decorated, you'd get ModelStateErrors.

**Comment by ickhov** [comment]
I implemented MyCustomerViewModel to handle Create and Edit function. It worked. I tested it to make sure states, country, and county wasn't being created every time a new customer was added.

**Comment by ickhov** [comment]
You should check it first.
