### ISSUE TITLE
Delete MyCustomers

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/CCIA#34]
You should create a [HTTPGet] Delete and [HTTPPost] Delete. First one shows similar to details (doesn't have to be full fields), second actually makes the delete. 

Also add a onclick="return confirm('Delete customer?')" whenever you have a delete. One extra chance for them to not do this.

**Comment by ickhov** [comment]
I created the GET and POST Delete and added the onclick return confirm as a second validation.

**Comment by ickhov** [comment]
You should check it first.
